apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinate-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coordinate-api
  template:
    metadata:
      labels:
        app: coordinate-api
    spec:
      containers:
      - name: coordinate-api
        image: sdbr1234/coordinate-api:v2
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_HOST
          value: "postgres-svc"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "coordinates_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"

        

